### ISSUE TITLE
Turn into rstan package

### ISSUE THREAD

**Issue by seananderson** [WGGRAFY/sarla#4]

**Comment by ChristineStawitz-NOAA** [comment]
I did this locally in a clean directory but trying to resolve it with the remote github repo

**Comment by ChristineStawitz-NOAA** [comment]
@seananderson how long does it typically take to load R packages with Stan models in it? It keeps taking a very long time to load which isn't great for testing.. I was getting some weird errors but I'm hoping some changes to `NAMESPACE` will fix it

**Comment by seananderson** [comment]
If the .stan template file has been altered then it will have to be recompiled when the package is built, but otherwise it shouldn't be any slower than usual. devtools::load_all() should be fastest (for the non C++ compiling part).

**Comment by ChristineStawitz-NOAA** [comment]
I tested it out on a new brand new machine and `devtools::load_all()` seems to work, so I think I have some weird setup on the old PC. I'm now testing to see if I can get sim-test to work. The new code is on the rstantools branch
